### GET ALL
GET http://localhost:3000/api/starships

### GET ONE BY ID
GET http://localhost:3000/api/starships/id/1

### POST
POST http://localhost:3000/api/starships
Content-Type: application/json

{
    "id": 1,
    "CodeName": "SN15",
    "rud": false,
    "numberOfStaticFires": 3,
    "testDate": "2021-05-05T22:24:00.000Z",
    "hop": "15KM",
    "scraped": false,
    "monument": true,
    "orbit": "nope",
    "owner": "SpaceX",
    "location": "Starbase, boca chica, TX, USA, Earth"
}